language: node_js
node_js:
  - "0.10"
  - "0.11"
services:
  - mongodb
  - rabbitmq
before_script:
  - npm install -g mocha
  - npm install -g istanbul
notifications:
  email:
    - jeffhann@gmail.com 
